# Generated by Django 2.1 on 2018-09-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicleid', models.IntegerField(db_column='vehicleID', primary_key=True, serialize=False)),
                ('makename', models.CharField(blank=True, db_column='makeName', max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('series', models.CharField(blank=True, max_length=50, null=True)),
                ('seriesyear', models.IntegerField(blank=True, db_column='seriesYear', null=True)),
                ('pricenew', models.DecimalField(blank=True, db_column='priceNew', decimal_places=2, max_digits=15, null=True)),
                ('enginesize', models.DecimalField(blank=True, db_column='engineSize', decimal_places=1, max_digits=2, null=True)),
                ('fuelsystem', models.CharField(blank=True, db_column='fuelSystem', max_length=50, null=True)),
                ('tankcapacity', models.DecimalField(blank=True, db_column='tankCapacity', decimal_places=1, max_digits=4, null=True)),
                ('power', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('seatingcapacity', models.IntegerField(blank=True, db_column='seatingCapacity', null=True)),
                ('standardtransmission', models.CharField(blank=True, db_column='standardTransmission', max_length=15, null=True)),
                ('bodytype', models.CharField(blank=True, db_column='bodyType', max_length=50, null=True)),
                ('wheeldrive', models.CharField(blank=True, db_column='wheelDrive', max_length=3, null=True)),
                ('wheelbase', models.DecimalField(blank=True, db_column='wheelBase', decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'vehicle',
                'managed': False,
            },
        ),
    ]
