# Generated by Django 2.1 on 2018-10-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_CarpCitypMonth',
            fields=[
                ('misCity', models.CharField(db_column='city', max_length=50, primary_key=True, serialize=False)),
                ('misMake', models.CharField(blank=True, db_column='make', max_length=50, null=True)),
                ('misModel', models.CharField(blank=True, db_column='model', max_length=50, null=True)),
                ('misMonth', models.CharField(blank=True, db_column='dateMonth', max_length=50, null=True)),
                ('misQuarter', models.IntegerField(blank=True, db_column='dateQuarter', null=True)),
                ('misYear', models.IntegerField(blank=True, db_column='dateYear', null=True)),
                ('misQuantity', models.IntegerField(blank=True, db_column='quantity', null=True)),
            ],
            options={
                'db_table': 'v_carpcitypmonth',
                'managed': False,
            },
        ),
    ]
