# Generated by Django 2.1 on 2018-09-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerid', models.IntegerField(db_column='customerID', primary_key=True, serialize=False)),
                ('customerfirstname', models.CharField(db_column='customerFirstName', max_length=50)),
                ('customerlastname', models.CharField(db_column='customerLastName', max_length=50)),
                ('customerdob', models.DateField(blank=True, db_column='customerDOB', null=True)),
                ('customeraddress', models.CharField(blank=True, db_column='customerAddress', max_length=50, null=True)),
                ('customeroccupation', models.CharField(blank=True, db_column='customerOccupation', max_length=50, null=True)),
                ('customergender', models.CharField(blank=True, db_column='customerGender', max_length=1, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customerphonenumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(db_column='phoneNumber', max_length=13)),
            ],
            options={
                'db_table': 'customerphonenumber',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeid', models.AutoField(db_column='employeeID', primary_key=True, serialize=False)),
                ('employeefirstname', models.CharField(db_column='employeeFirstName', max_length=50)),
                ('employeelastname', models.CharField(db_column='employeeLastName', max_length=50)),
                ('employeedob', models.DateField(blank=True, db_column='employeeDOB', null=True)),
                ('employeeaddress', models.CharField(blank=True, db_column='employeeAddress', max_length=50, null=True)),
                ('employeecity', models.CharField(blank=True, db_column='employeeCity', max_length=50, null=True)),
                ('employeestate', models.CharField(blank=True, db_column='employeeState', max_length=3, null=True)),
                ('employeeemail', models.CharField(blank=True, db_column='employeeEmail', max_length=100, null=True)),
                ('employeephonenumber', models.IntegerField(blank=True, db_column='employeePhoneNumber', max_length=20, null=True)),
                ('employeeusername', models.CharField(blank=True, db_column='employeeUsername', max_length=50, null=True)),
                ('employeepassword', models.CharField(blank=True, db_column='employeePassword', max_length=100, null=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employeerole',
            fields=[
                ('roleid', models.AutoField(db_column='roleID', primary_key=True, serialize=False)),
                ('rolename', models.CharField(db_column='roleName', max_length=30)),
                ('roleaccesslevel', models.IntegerField(db_column='roleAccessLevel')),
            ],
            options={
                'db_table': 'employeerole',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salesorder',
            fields=[
                ('orderid', models.IntegerField(db_column='orderID', primary_key=True, serialize=False)),
                ('createdate', models.DateField(blank=True, db_column='createDate', null=True)),
                ('pickupdate', models.DateField(blank=True, db_column='pickupDate', null=True)),
                ('returndate', models.DateField(blank=True, db_column='returnDate', null=True)),
            ],
            options={
                'db_table': 'salesorder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('storeid', models.IntegerField(db_column='storeID', primary_key=True, serialize=False)),
                ('storename', models.CharField(blank=True, db_column='storeName', max_length=50, null=True)),
                ('storeaddress', models.CharField(blank=True, db_column='storeAddress', max_length=50, null=True)),
                ('storephonenumber', models.CharField(blank=True, db_column='storePhoneNumber', max_length=13, null=True)),
                ('storecity', models.CharField(blank=True, db_column='storeCity', max_length=50, null=True)),
                ('storestate', models.CharField(blank=True, db_column='storeState', max_length=3, null=True)),
            ],
            options={
                'db_table': 'store',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicleid', models.IntegerField(db_column='vehicleID', primary_key=True, serialize=False)),
                ('makename', models.CharField(blank=True, db_column='makeName', max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('series', models.CharField(blank=True, max_length=50, null=True)),
                ('seriesyear', models.IntegerField(blank=True, db_column='seriesYear', null=True)),
                ('pricenew', models.DecimalField(blank=True, db_column='priceNew', decimal_places=2, max_digits=15, null=True)),
                ('enginesize', models.DecimalField(blank=True, db_column='engineSize', decimal_places=1, max_digits=2, null=True)),
                ('fuelsystem', models.CharField(blank=True, db_column='fuelSystem', max_length=50, null=True)),
                ('tankcapacity', models.DecimalField(blank=True, db_column='tankCapacity', decimal_places=1, max_digits=4, null=True)),
                ('power', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('seatingcapacity', models.IntegerField(blank=True, db_column='seatingCapacity', null=True)),
                ('standardtransmission', models.CharField(blank=True, db_column='standardTransmission', max_length=15, null=True)),
                ('bodytype', models.CharField(blank=True, db_column='bodyType', max_length=50, null=True)),
                ('wheeldrive', models.CharField(blank=True, db_column='wheelDrive', max_length=3, null=True)),
                ('wheelbase', models.DecimalField(blank=True, db_column='wheelBase', decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'vehicle',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
