# Generated by Django 2.1 on 2018-10-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20180917_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citylist',
            fields=[
                ('cityid', models.IntegerField(db_column='cityID', primary_key=True, serialize=False)),
                ('cityname', models.CharField(blank=True, db_column='cityName', max_length=50, null=True)),
                ('citystate', models.CharField(blank=True, db_column='cityState', max_length=5, null=True)),
                ('citycountry', models.CharField(blank=True, db_column='cityCountry', max_length=50, null=True)),
            ],
            options={
                'db_table': 'citylist',
                'ordering': ['cityid'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V_CarpCitypMonth',
            fields=[
                ('misCity', models.CharField(db_column='city', max_length=50, primary_key=True, serialize=False)),
                ('misMake', models.CharField(blank=True, db_column='make', max_length=50, null=True)),
                ('misModel', models.CharField(blank=True, db_column='model', max_length=50, null=True)),
                ('misMonth', models.CharField(blank=True, db_column='dateMonth', max_length=50, null=True)),
                ('misQuarter', models.IntegerField(blank=True, db_column='dateQuarter', null=True)),
                ('misYear', models.IntegerField(blank=True, db_column='dateYear', null=True)),
                ('misQuantity', models.IntegerField(blank=True, db_column='quantity', null=True)),
            ],
            options={
                'db_table': 'v_carpcitypmonth',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V_Cities',
            fields=[
                ('mis_cityID', models.IntegerField(db_column='cityID', primary_key=True, serialize=False)),
                ('mis_cityName', models.CharField(db_column='cityName', max_length=50)),
            ],
            options={
                'db_table': 'v_cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V_PickupDiffCarsCity',
            fields=[
                ('psPickupCityID', models.IntegerField(db_column='cityID')),
                ('psPickupCity', models.CharField(db_column='pickupCity', max_length=50, primary_key=True, serialize=False)),
                ('psDateMonth', models.CharField(blank=True, db_column='dateMonth', max_length=50, null=True)),
                ('psDateQuarter', models.IntegerField(blank=True, db_column='dateQuarter', null=True)),
                ('psYear', models.IntegerField(blank=True, db_column='dateYear', null=True)),
                ('psNumDiffCars', models.IntegerField(blank=True, db_column='quantity', null=True)),
            ],
            options={
                'db_table': 'v_pickupdiffcarscity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V_ReturnDiffCarsCity',
            fields=[
                ('prReturnCityID', models.IntegerField(db_column='cityID')),
                ('prReturnCity', models.CharField(db_column='returnCity', max_length=50, primary_key=True, serialize=False)),
                ('prDateMonth', models.CharField(blank=True, db_column='dateMonth', max_length=50, null=True)),
                ('prDateQuarter', models.IntegerField(blank=True, db_column='dateQuarter', null=True)),
                ('prYear', models.IntegerField(blank=True, db_column='dateYear', null=True)),
                ('prNumDiffCars', models.IntegerField(blank=True, db_column='quantity', null=True)),
            ],
            options={
                'db_table': 'v_returndiffcarscity',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False, 'ordering': ['customerid']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': False, 'ordering': ['employeeid']},
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={'managed': False, 'ordering': ['orderid']},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'managed': False, 'ordering': ['storeid']},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'managed': False, 'ordering': ['vehicleid']},
        ),
    ]
