# Generated by Django 2.1 on 2018-10-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20181007_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': True, 'ordering': ['employeeid']},
        ),
    ]
