# Generated by Django 2.1 on 2018-10-25 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_merge_20181023_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citylist',
            options={'ordering': ['cityid']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['customerid']},
        ),
        migrations.AlterModelOptions(
            name='customerphonenumber',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['employeeid']},
        ),
        migrations.AlterModelOptions(
            name='employeerole',
            options={},
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['orderid']},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['storeid']},
        ),
        migrations.AlterModelOptions(
            name='v_carpcitypmonth',
            options={},
        ),
        migrations.AlterModelOptions(
            name='v_cities',
            options={},
        ),
        migrations.AlterModelOptions(
            name='v_pickupdiffcarscity',
            options={},
        ),
        migrations.AlterModelOptions(
            name='v_returndiffcarscity',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={},
        ),
    ]
