# Generated by Django 2.1 on 2018-10-25 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20181025_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employeeeloginattempt',
            new_name='employeeloginattempt',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employeecity',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employeestate',
        ),
        migrations.RemoveField(
            model_name='store',
            name='storecity',
        ),
        migrations.RemoveField(
            model_name='store',
            name='storestate',
        ),
        migrations.AddField(
            model_name='customerphonenumber',
            name='customerid',
            field=models.ForeignKey(db_column='customerID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.Customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='employeecityid',
            field=models.ForeignKey(blank=True, db_column='employeeCityID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.Citylist'),
        ),
        migrations.AddField(
            model_name='employee',
            name='roleid',
            field=models.ForeignKey(blank=True, db_column='roleID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.Employeerole'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customerid',
            field=models.ForeignKey(blank=True, db_column='customerID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.Customer'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='pickupstoreid',
            field=models.ForeignKey(blank=True, db_column='pickupStoreID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pickupStoreID', to='employees.Store'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='returnstoreid',
            field=models.ForeignKey(blank=True, db_column='returnStoreID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='returnStoreID', to='employees.Store'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='vehicleid',
            field=models.ForeignKey(blank=True, db_column='vehicleID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.Vehicle'),
        ),
        migrations.AddField(
            model_name='store',
            name='storecityid',
            field=models.ForeignKey(blank=True, db_column='storeCityID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.Citylist'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeephonenumber',
            field=models.IntegerField(blank=True, db_column='employeePhoneNumber', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='customerphonenumber',
            unique_together={('customerid', 'phonenumber')},
        ),
        migrations.AlterUniqueTogether(
            name='v_carpcitypmonth',
            unique_together={('misCity', 'misMake', 'misModel', 'misMonth', 'misQuarter', 'misYear', 'misQuantity')},
        ),
        migrations.AlterUniqueTogether(
            name='v_pickupdiffcarscity',
            unique_together={('psPickupCityID', 'psPickupCity', 'psDateMonth', 'psDateQuarter', 'psYear', 'psNumDiffCars')},
        ),
        migrations.AlterUniqueTogether(
            name='v_returndiffcarscity',
            unique_together={('prReturnCityID', 'prReturnCity', 'prDateMonth', 'prDateQuarter', 'prYear', 'prNumDiffCars')},
        ),
    ]
