# Generated by Django 2.1 on 2018-10-11 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20181007_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employeeeloginattempt',
            field=models.IntegerField(db_column='employeeLoginAttempt', default=0),
        ),
    ]
