# Generated by Django 2.1 on 2018-10-23 10:33


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20181011_1906'),
        ('employees', '0003_auto_20181008_1557'),
    ]

    operations = [
		migrations.AddField(
            model_name='employee',
            name='employeeemailverify',
            field=models.CharField(db_column='employeeEmailVerify', default='0', max_length=40),
        ),
		migrations.AddField(
            model_name='employee',
            name='employeeeloginattempt',
            field=models.IntegerField(db_column='employeeLoginAttempt', default=0),
        ),
    ]
